channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==2.2.1
  - numpy==1.24.2
  - pandas==1.5.3
  - torch==2.2.2
  - tqdm==4.67.1
name: mlflow-env
